name: User Service CI

on:
  push:
    paths:
      - "user-service/**"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: |
          docker build \
          -t user-service \
          ./user-service

      - name: Tag Image
        run: |
          docker tag user-service:latest \
          106551436513.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/user-service:latest

      - name: Push Image
        run: |
          docker push \
          106551436513.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/user-service:latest
